export * from "./types";
export * from "./inventory-location";
export * from "./schema";
export * from "./loader";
export * from "./compiler";
export * from "./simulator";
export * from "./evaluator";
export * from "./artifacts";
export * from "./research";
export * from "./frontend";
export * from "./utils";
export * from "./rng";
export * from "./state";
export * from "./device-runtime";
export * from "./dispatch-priority";
export * from "./workspace";
export * from "./production-analysis";
export * from "./capacity-plan";
export * from "./synthesis";
export * from "./project-synthesis";
export * from "./routing";
export * from "./logistics-capacity";
export * from "./production-demand";
export * from "./blueprint-comparison";
export * from "./power-envelope";
export * from "./benchmark";
export * from "./benchmark-case-execution";
export * from "./candidate-change-set";
export * from "./candidate-review";
export * from "./design-program";
export * from "./design-run";
export * from "./design-proposal-provider";
export * from "./fab-loss-analysis";
export * from "./transport-blocking";
export * from "./workbench";
export * from "./observation";
export * from "./investigation";
export * from "./artifact-schema";
export * from "./operation";
export * from "./objective-constraints";
export * from "./operation-execution";
export * from "./studio-source-identity";
export * from "./execution-identity";

import { compileFactoryProject } from "./compiler";
import { loadFactoryProject, type ProjectSelection } from "./loader";

export async function openFactoryProject(projectDir: string, selection: ProjectSelection = {}) {
  return compileFactoryProject(await loadFactoryProject(projectDir, selection));
}
